[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
crossterm = "0.28.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
